language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 0yVrUYHb8X4QJCzsl4ilmSoQBdfr9KQyHBvyV0rgp5yaHLqtvLb5qjV0J4i92qZvT2jKCWkIYv737QvDJRWPAg61rrxZFCqTF/j+Hjd7A0enxg8GKY8XtzwmyYJzEZz6IWyXrq85k98Hl18wi3FJuHLFcNpAbdceObdnNwMmwPTGEzYVAoxi/OctLOfx89UCHOhrPf/4J6hIijSM4EgSJE3ktfHInu9zy8hoKI9uw7T7AscuauWaVVQkKVyqd7qHYZfQSmmf7azQtE3dcB43BFDyU+xt43FKceioGcPIdXVl1fxW0puhGvlAtql3VefQPTlV4kuoZrFv672URLUsQgKh2UXaLpNDXEdFsSE6+yqmglfiy2XPcQeB3Ug53EWq5eRIrhuYU4bAuW3+rCI2hn1PJcimTtizZrH9RN4QguHP5lIUh4Wzxw1iW0hutW+FiFZGcDa02U1dPs2V58ssiz3Em1gts6XhSUphcz2wTyeKVh3T2lFrYpQgK3gMn2mbUehZM3fhTy4RuyOCNAR5MPo/zWjfgYqm4zbxKoVSL8MeDmV/9+qR7INOlr44l+NCzO0tp1/uM94BRhdPL8SWx2ZI1ddjyUYoCmqibEca6vg/cAiadpvxkl4n81bx0hPXB7N8n0XmnKVaQR/VSJAXckRckI7PPV3HGdXxFa8/PYE=
  app: takehome-project
  on:
    repo: imagineLife/takehome
